import React from 'react'

const PrivacyPolicy = () => {
  return (
    <>
   <div className='m-2'>
   <span className='text-4xl font-mono text-black mb-2 underline-offset-8'>Privacy Policy</span>
   <div className='items-center justify-center m-4 w-5/6'>
 <h2 className='text-black text-xl lg:text-2xl'>  Daily Purba-Paschim is firm to protect your personal information when you are using the website or applications from Daily Purba-Paschim. This privacy policy relates to use of any personal information that it collects from visitors/readers via following, among other, services:
 </h2>
 <ul className='list-decimal ml-7'>
    <li className='text-xl font-serif text-black'>any Daily Purba-Paschim website that links to this privacy policy;</li>
    <li className='text-xl font-serif text-black'>social media or official Daily Purba-Paschim content on other websites;</li>
    <li className='text-xl font-serif text-black'>mobile and web applications (Apps)</li>

 </ul>
 <div className='text-xl font-serif text-black'>
  <h1>
  In all the above services, the “privacy policy” shall apply only when the application, website or contents therein are truly and genuinely generated by Daily Purba-Paschim. Provided that no application, website or contents therein are generated or presented at any false or fake website, page or group in the name (or with false logo) of Daily Purba-Paschim, won’t get this protection.
  <br className='gap-3' />
  Daily Purba-Paschim collects or receives information about its users for many purposes; for instance, to provide services designed to serve the user, to monitor and improve the services offerings, for marketing or targeting advertisements etc. Such information may include your name, address, phone number, email address, age, social network account etc.
  <br className='gap-3'/>
  There may be other privacy policies that apply to certain services provided by Daily Purba-Paschim. Visitors are requested to read these while registering or subscribing to these services on these sites. Daily Purba-Paschim respects the privacy of its visitors/readers and makes use of its best effort to ensure that the information collected is used for the limited purpose for which it was received.
  </h1>
  <h1 className='text-black font-serif text-2xl font-semibold'>Special Precaution</h1>
  <h1>In the name of Daily Purba-Paschim there may be multiple fake websites and facebook pages and unauthorized/ unwanted facebook groups in online. Daily Purba-Paschim will hold no responsibility for any content generated, published or shared in those fake websites, unauthorized pages or groups in social media.</h1>
<h1 className='text-black font-serif text-2xl font-semibold'>How Daily Purba-Paschim collects the information</h1>
<h1>Daily Purba-Paschim collects the information on a user upon the user’s access to the Daily Purba-Paschim website – (i) by registering to the site or Apps, (ii) subscribing to the newsletter, (iii) responding to a survey or participating in a competition, (iv) logging-in to a site or page, etc.</h1>
<h1 className='text-black font-serif text-2xl font-semibold'>Disclosure of Information Collected</h1>
<h1>
Daily Purba-Paschim does not trade or provide personally identifiable information to any other parties except for those that assist Daily Purba-Paschim in operating its website, conducting the business and serving the users.
<br className='gap-3'/>Daily Purba-Paschim may release personally identifiable information if it is required to comply with the laws of Bangladesh.
<br className='gao-3' /> Notwithstanding anything contained in this privacy policy, Daily Purba-Paschim may disclose or share information collected including personal information to service providers, affiliate companies, consultants or advisors or partners that it has engaged to perform business related functions on its behalf. Daily Purba-Paschim may also share the information in response to legal process, or protect its interest in any forum. The information may be used for investigating or preventing potentially illegal activities, or situations involving potential threats to any person, us, or the services, or violations of our policies, the law or our “Terms of Use” as well as to verify or enforce compliance with the policies governing our services.
<br className='gap-3' />The information may as well be shared to offer market products or services to the visitors/readers. However, in all these events or any other event when personal information is shared or disclosed, Daily Purba-Paschim will use its best endeavors to control the sharing or disclosure and will only share to such an extent as it is required to meet the purpose.

</h1>
<h1 className='text-black font-serif text-2xl font-semibold'>Advertisement</h1>
<h1>
The advertisements included in the Daily Purba-Paschim website and Apps, are by third-party companies and ad networks through independent ad tags, which may collect information about users for which Daily Purba-Paschim will bear no responsibility that may arise as a result of collecting and/or sharing the information with any other party.
<br className='gap-3'/>
Daily Purba-Paschim will not accept any liability that may arise as a result of any content of any advertisement that may appear on the Daily Purba-Paschim website.

</h1>
<h1 className='text-black font-serif text-2xl font-semibold'>Third Party Advertisements and links</h1>
<h1>At the discretion of Daily Purba-Paschim, the website or application may display or allow advertisements of third party services or products. These third-party sites may have separate and independent privacy policies. Daily Purba-Paschim accepts no responsibility or liability for the content of advertising material, including, without limitation, any error, omission or inaccuracy therein..
  <br  className='gap-3'/>
  Daily Purba-Paschim does not hold any responsibility for information leakage due to the visitor/reader accessing a separate link, application or website, whether through a link in the website or contents of Daily Purba-Paschim.
</h1>

<h1 className='text-black font-serif text-2xl font-semibold'>Modification of Privacy Policy</h1>
<h1>Daily Purba-Paschim reserves the right to amend, modify, alter, or omit any terms in the “Privacy Policy” at any time but the changed policy will be immediately uploaded or updated in the website. By continuing to use our services after any changes are made, you accept those changes and will be bound by them. We encourage you to periodically check back and review this policy so that visitors/readers will always know what information we collect, how we use it, and with whom we share it.</h1>

Purba-Paschim 






 </div>

 

   </div>
   </div>
    </>
  )
}

export default PrivacyPolicy